package com.guipadovan.ecms.domain;

public enum Permission {

    ACCESS_DASHBOARD, ACCESS_CONFIG, ACCESS_USERS, ACCESS_ROLES, ACCESS_ADD_ROLE, ACCESS_POSTS, ACCESS_ADD_POST,
    POST_EDIT, POST_DELETE, POST_COMMENT, POST_REACT, POST_LOCK,
    MODERATE_BAN, MODERATE_UNBAN,

}
