server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: estore
    password: root
    url: jdbc:mysql://localhost:3306/ecms
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

jwt:
  auth:
    app: ecms
    secret_key: ecms8888888
    expiration:
      access: 5
      refresh: 1440

config:
  email: "contato@exitius.com"
  master-user:
    username: Guii
    email: "guipadovam@gmail.com"
    password: asd123
  master-role: Admin
  default-role: User
